---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(ggplot2)
library(latex2exp)
library(patchwork)
```

# Misclassification Error

```{r}
## Figure: S1a
eta1 = as.data.frame(t(read.csv("../table/accuracy/eta_1.csv")[,-1]))
eta2 = as.data.frame(t(read.csv('../table/accuracy/eta_2.csv')[,-1]))
eta3 = as.data.frame(t(read.csv('../table/accuracy/eta_3.csv')[,-1]))

eta1$Error = "Empirical Misclassification Rate"
eta1$eta = seq(0,0.1,0.01)
eta1 = eta1[-1,]
eta2$Error = "Empirical Misclassification Rate"
eta2$eta = seq(0,0.1,0.01)
eta2 = eta2[-1,]
w = data.frame('V1' = seq(0.01,0.1,0.01))
w$eta = seq(0.01,0.1,0.01)
w$Error = "Target Misclassification Rate"
eta1 = rbind(eta1,w)
eta2 = rbind(eta2,w)
eta1$setting = "Setting 1"
eta2$setting = "Setting 2"
eta3$Error = "Empirical Misclassification Rate"
eta3$eta = seq(0,0.1,0.01)
eta3 = eta3[-1,]
eta3 = rbind(eta3,w)
eta3$setting = "Setting 3"

eta.data = rbind(eta1,eta2,eta3)


ggplot(data=eta.data, aes(x= eta, y = V1, group = Error))+
  geom_line(linetype = "dashed",aes(color = Error))+
  geom_point(aes(color = Error))+
  facet_grid(cols = vars(setting))+ 
  ylim(0,0.3)+
  xlab(TeX("Target Misclassification Rate($\\eta$)"))+ 
  ylab("Misclassification Rate")+
  theme_bw()
```


```{r}
## Figure: S1b
eta1 = as.data.frame(t(read.csv("../table/accuracy/eta_4.csv")[,-1]))
eta2 = as.data.frame(t(read.csv('../table/accuracy/eta_5.csv')[,-1]))
eta3 = as.data.frame(t(read.csv('../table/accuracy/eta_6.csv')[,-1]))

eta1$Error = "Empirical Misclassification Rate"
eta1$gamma = seq(0.5,0.95,0.05)
eta2$Error = "Empirical Misclassification Rate"
eta2$gamma = seq(0.5,0.95,0.05)
w = data.frame('V1' = rep(0.1,10))
w$gamma = seq(0.5,0.95,0.05)
w$Error = "Target Misclassification Rate"
eta1 = rbind(eta1,w)
eta2 = rbind(eta2,w)
eta1$setting = "Setting 1"
eta2$setting = "Setting 2"
eta3$Error = "Empirical Misclassification Rate"
eta3$gamma = seq(0.5,0.95,0.05)
eta3 = rbind(eta3,w)
eta3$setting = "Setting 3"

eta.data = rbind(eta1,eta2,eta3)

ggplot(data=eta.data, aes(x= gamma, y = V1, group = Error))+
  geom_line(linetype = "dashed",aes(color = Error))+
  geom_point(aes(color = Error))+
  facet_grid(cols = vars(setting))+ 
  ylim(0,0.3)+
  xlab(expression(gamma))+ 
  ylab("Misclassification Rate")+
  theme_bw()
```


```{r}
# Figure S3
effect_size <- read.csv('../table/accuracy/lambda.csv')
colnames(effect_size) = c('Value','error')


u <- read.csv('../table/accuracy/dag.csv')[-1]
dagfrac = data.frame('error' = as.numeric(u[1,]))
dagfrac$Value = seq(0.1,0.5,0.1)


size <- read.csv('../table/accuracy/Size.csv')[-1,]
size[,1] = c(100,300,500)
colnames(size) = c('Value','error')


uneven <- read.csv('../table/accuracy/uneven.csv')
uneven[,1] = seq(0.1,0.4,0.1)
colnames(uneven) = c('Value','error')

p1 = ggplot(data=effect_size, aes(x= Value, y = error))+
  geom_line(linetype = "dashed",color = "#FF9999")+
  geom_point(color = "#FF9999")+
  ylim(0,0.05)+
  xlab("Signal Strength")+
  ylab("Misclassification Rate")+
  scale_x_continuous(expand = expansion(mult = .2))+
  theme_bw()
p2 = ggplot(data=dagfrac, aes(x= Value, y = error))+
  geom_line(linetype = "dashed",color = "#FF9999")+
  geom_point(color = "#FF9999")+
  ylim(0,0.05)+
  xlab("Proportion of Differential Abundant Taxa")+
  ylab("Misclassification Rate")+
  scale_x_continuous(expand = expansion(mult = .2))+
  theme_bw()
p3 = ggplot(data=size, aes(x= Value, y = error))+
  geom_line(linetype = "dashed",color = "#FF9999")+
  geom_point(color = "#FF9999")+
  ylim(0,0.05)+
  xlab("Sample Size")+
  ylab("Misclassification Rate")+
  scale_x_continuous(expand = expansion(mult = .2))+
  theme_bw()
p4 = ggplot(data=size, aes(x= Value, y = error))+
  geom_line(linetype = "dashed",color = "#FF9999")+
  geom_point(color = "#FF9999")+
  ylim(0,0.05)+
  xlab("Group 1 Size:Group 2 Size")+
  ylab("Misclassification Rate")+
  scale_x_continuous(expand = expansion(mult = .2))+
  theme_bw()

p = p1+p2+p3+p4
p + plot_layout(ncol = 2,guides = "collect")& theme(legend.position = "bottom")
```

```{r}
# Figure S2a
power_eta_mirk = read.csv("../table/twosample/eta-mirk.csv")[,-1]
power_eta_perm = read.csv("../table/twosample/eta-perm.csv")[,-1]
power_eta = data.frame('Power' = c(t(power_eta_mirk[1,]),t(power_eta_perm[1,])),"eta" = rep(seq(0,0.5,0.05),2),"Test" = c(rep('MiRKAT',11),rep("PERMANOVA",11)))


p1 = ggplot(data=power_eta, aes(x=eta, y=Power))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  facet_grid(cols = vars(Test))+    
  xlab(expression(eta)) + 
  ylab("Power")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

power_gamma_mirk = read.csv("../table/twosample/gamma-mirk.csv")[,-1]
power_gamma_perm = read.csv("../table/twosample/gamma-perm.csv")[,-1]
power_gamma = data.frame('Power' = c(t(power_gamma_mirk[1,]),t(power_gamma_perm[1,])),"gamma" = rep(seq(0,0.9,0.1),2),"Test" = c(rep('MiRKAT',10),rep("PERMANOVA",10)))

p2 = ggplot(data=power_gamma, aes(x=gamma, y=Power))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  facet_grid(cols = vars(Test))+    
  xlab(expression(gamma)) + 
  ylab("Power")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))


p = p1+p2
p+plot_layout(ncol = 1)
```

```{r}
# Figure S2b
typeI_eta_mirk = read.csv("../table/twosample/typeI-eta-mirk.csv")[,-1]
typeI_eta_perm = read.csv("../table/twosample/typeI-eta-perm.csv")[,-1]
typeI_eta = data.frame('Error' = c(t(typeI_eta_mirk[1,]),t(typeI_eta_perm[1,])),"eta" = rep(seq(0,0.5,0.05),2),"Test" = c(rep('MiRKAT',11),rep("PERMANOVA",11)))


p1 = ggplot(data=typeI_eta, aes(x=eta, y=Error))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +  
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  facet_grid(cols = vars(Test))+    
  xlab(expression(eta)) + 
  ylab("Type I Error")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))


typeI_gamma_mirk = read.csv("../table/twosample/typeI-gamma-mirk.csv")[,-1]
typeI_gamma_perm = read.csv("../table/twosample/typeI-gamma-perm.csv")[,-1]
typeI_gamma = data.frame('Error' = c(t(typeI_gamma_mirk[1,]),t(typeI_gamma_perm[1,])),"gamma" = rep(seq(0,0.9,0.1),2),"Test" = c(rep('MiRKAT',10),rep("PERMANOVA",10)))

p2 = ggplot(data=typeI_gamma, aes(x=gamma, y=Error))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +  
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  facet_grid(cols = vars(Test))+    
  xlab(expression(gamma)) + 
  ylab("Type I Error")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))


p = p1+p2
p+plot_layout(ncol = 1)
```

```{r}
pearson_gamma = read.csv("../table/pearson/gamma_sensitivity.csv")[,-1]
da_gamma = data.frame('Sensitivity' = pearson_gamma,"gamma" = seq(0,0.9,0.1))

p1 = ggplot(data=da_gamma, aes(x=gamma, y=Sensitivity))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(gamma)) + 
  ylab("Sensitivity")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

t_gamma = read.csv("../table/t/gamma_sensitivity.csv")[,-1]
da_gamma = data.frame('Sensitivity' = t_gamma,"gamma" = seq(0,0.9,0.1))

p2 = ggplot(data=da_gamma, aes(x=gamma, y=Sensitivity))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(gamma)) + 
  ylab("Sensitivity")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

pearson_gamma = read.csv("../table/pearson/gamma_FDR.csv")[,-1]
da_gamma = data.frame('FDR' = pearson_gamma,"gamma" = seq(0,0.9,0.1))

p3 = ggplot(data=da_gamma, aes(x=gamma, y=FDR))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(gamma)) + 
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  ylab("FDR")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

t_gamma = read.csv("../table/t/gamma_FDR.csv")[,-1]
da_gamma = data.frame('FDR' = t_gamma,"gamma" = seq(0,0.9,0.1))

p4 = ggplot(data=da_gamma, aes(x=gamma, y=FDR))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(gamma)) + 
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  ylab("FDR")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

pearson_eta = read.csv("../table/pearson/eta_sensitivity.csv")[,-1]
da_eta = data.frame('Sensitivity' = pearson_eta,"eta" = seq(0,0.5,0.05))

p5 = ggplot(data=da_eta, aes(x=eta, y=Sensitivity))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(eta)) + 
  ylab("Sensitivity")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

t_eta = read.csv("../table/t/eta_sensitivity.csv")[,-1]
da_eta = data.frame('Sensitivity' = t_eta,"eta" = seq(0,0.5,0.05))

p6 = ggplot(data=da_eta, aes(x=eta, y=Sensitivity))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(eta)) + 
  ylab("Sensitivity")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

pearson_eta = read.csv("../table/pearson/eta_FDR.csv")[,-1]
da_eta = data.frame('FDR' = pearson_eta,"eta" = seq(0,0.5,0.05))

p7 =  ggplot(data=da_eta, aes(x=eta, y=FDR))+ 
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(eta)) + 
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  ylab("FDR")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))

t_eta = read.csv("../table/t/eta_FDR.csv")[,-1]
da_eta = data.frame('FDR' = t_eta,"eta" = seq(0,0.5,0.05))

p8 = ggplot(data=da_eta, aes(x=eta, y=FDR))+
  geom_line(linetype = "solid",color = "#FF9999")+
  geom_point(color = "#FF9999") +                        
  xlab(expression(eta))+ 
  geom_abline(intercept = 0.05,slope = 0,color = "black",alpha = 0.5, linetype = "dashed")+
  ylab("FDR")+
  ylim(0,1)+
  theme_bw()+
  theme(legend.text = element_text(size=10))
```

```{r}
# S2c
p = p5+p7+p1+p3
p+plot_layout(ncol = 2)
```


```{r}
# S2d
p = p6+p8+p2+p4
p+plot_layout(ncol = 2)
```


# Sampling Fraction

```{r}
sf.table = function(X,method){
  X1 = read.csv(X)[,-1]
  res1 = data.frame(Bias = c(t(abs(X1[1,])),t(abs(X1[2,])),t(abs(X1[3,]))))
  res1$lambda = c(1,10,100)
  res1$p = as.factor(c(rep("p=0.1",3),rep("p=0.2",3),rep("p=0.3",3)))
  res1$Method = method
  return(res1)
}
```

```{r}
# sf
files = list.files(path = "../table/sampling_fraction/", full.names = TRUE)

table = NULL
method = c('CSS','GMPR','MED','RSim','TMM','TSS','UQ')
for(i in 1:length(files)){
  if(is.null(table)){
    table = sf.table(files[i],method[i])
  }else{
  table = rbind(table,sf.table(files[i],method[i]))
  }
}

# Figure 2d
table$Method = factor(table$Method,level = c('RSim','CSS','MED','TMM','TSS','UQ','GMPR'))

ggplot(data=table, aes(x=as.factor(lambda), y=Bias, fill=Method))+
geom_bar(stat="identity",
         position=position_dodge(),
         size=.1,
        ) +                        # Thinner lines
scale_fill_brewer(palette = "Set2")+
facet_grid(cols = vars(p))+    # Set legend title
xlab("Signal Strength") + 
ylab("Bias")+
coord_flip()+
theme_bw()+
theme(legend.text = element_text(size=10))
ggsave("Fig2d.png", units="in", width=6, height=2.7, dpi=300)
```

# Differential Abundant Test

```{r}
sensitivity.table = function(X,method){
  X1 = read.csv(X)[,-1]
  res1 = data.frame(Sensitivity = c(t(X1[1,]),t(X1[2,]),t(X1[3,])))
  res1$lambda = c(100,200,300)
  res1$m = as.factor(c(rep(100,3),rep(200,3),rep(300,3)))
  res1$Method = method
  return(res1)
}
```

```{r}
FDR.table = function(X,method){
  X1 = read.csv(X)[,-1]
  res1 = data.frame(FDR = c(t(X1[1,]),t(X1[2,]),t(X1[3,])))
  res1$lambda = c(100,200,300)
  res1$m = as.factor(c(rep(100,3),rep(200,3),rep(300,3)))
  res1$Method = method
  return(res1)
}
```

##  t-test

```{r}
# Figure 5a
files = list.files(path = "../table/t/", pattern = "\\_sensitivity.csv$", full.names = TRUE)

table = NULL
method = c('CSS','GMPR','MED','Unnormalized','RSim','TMM','TSS','UQ')
for(i in 1:length(files)){
  if(is.null(table)){
    table = sensitivity.table(files[i],method[i])
  }else{
  table = rbind(table,sensitivity.table(files[i],method[i]))
  }
}
table$Method = factor(table$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR'))

ggplot(data=table, aes(x= lambda, y = Sensitivity, group = m))+
  geom_line(linetype = "solid",aes(colour=m))+
  geom_point(aes(colour=m))+                    
  facet_grid(cols = vars(Method))+    
  xlab("Signal Strength")+ 
  ylab("Sensitivity")+
  theme_bw()+
  labs(colour = "Sample Size")+
  ylim(0.8,1)+
  theme()
ggsave("Fig5a.png", units="in", width=13, height=2, dpi=300)
```

```{r}
# Figure 5b
files = list.files(path = "../table/t/", pattern = "\\_FDR.csv$", full.names = TRUE)

table = NULL
for(i in 1:length(files)){
  if(is.null(table)){
    table = FDR.table(files[i],method[i])
  }else{
  table = rbind(table,FDR.table(files[i],method[i]))
  }
}
table$Method = factor(table$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR'))

ggplot(data=table, aes(x= lambda, y = FDR, group = m))+
  geom_line(linetype = "solid",aes(colour=m))+
  geom_point(aes(colour=m))+                    # Thinner lines
  facet_grid(cols = vars(Method))+    # Set legend title
  xlab("Signal Strength")+ 
  ylab("FDR")+
  theme_bw()+
  ylim(0,1)+
  geom_hline(yintercept=0.1, linetype="dashed", 
            color = "black", size=0.5)+
  labs(colour = "Sample Size")
ggsave("Fig5b.png", units="in", width=13, height=2, dpi=300)
```


## pearson correlation test

```{r}
sensitivity.table = function(X,method){
  X1 = read.csv(X)[,-1]
  res1 = data.frame(Sensitivity = c(t(X1[1,]),t(X1[2,]),t(X1[3,])))
  res1$lambda = c(50,100,150)
  res1$m = as.factor(c(rep(200,3),rep(350,3),rep(500,3)))
  res1$Method = method
  return(res1)
}
```

```{r}
FDR.table = function(X,method){
  X1 = read.csv(X)[,-1]
  res1 = data.frame(FDR = c(t(X1[1,]),t(X1[2,]),t(X1[3,])))
  res1$lambda = c(50,100,150)
  res1$m = as.factor(c(rep(200,3),rep(350,3),rep(500,3)))
  res1$Method = method
  return(res1)
}
```

```{r}
# Figure 5c
files = list.files(path = "../table/pearson/", pattern = "\\_sensitivity.csv$", full.names = TRUE)

table = NULL
for(i in 1:length(files)){
  if(is.null(table)){
    table = sensitivity.table(files[i],method[i])
  }else{
  table = rbind(table,sensitivity.table(files[i],method[i]))
  }
}

table$Method = factor(table$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR'))
ggplot(data=table, aes(x= lambda, y = Sensitivity, group = m))+
  geom_line(linetype = "solid",aes(colour=m))+
  geom_point(aes(colour=m))+                    # Thinner lines
  facet_grid(cols = vars(Method))+    # Set legend title
  xlab("Signal Strength")+ 
  ylab("Sensitivity")+
  theme_bw()+
  labs(colour = "Sample Size")+
  theme(legend.text = element_text(size=5))
ggsave("Fig5c.png", units="in", width=13, height=2, dpi=300)
```

```{r}
# Figure 5d
files = list.files(path = "../table/pearson/", pattern = "\\_FDR.csv$", full.names = TRUE)

table = NULL
for(i in 1:length(files)){
  if(is.null(table)){
    table = FDR.table(files[i],method[i])
  }else{
  table = rbind(table,FDR.table(files[i],method[i]))
  }
}
table$Method = factor(table$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR'))

ggplot(data=table, aes(x= lambda, y = FDR, group = m))+
  geom_line(linetype = "solid",aes(colour=m))+
  geom_point(aes(colour=m))+                    # Thinner lines
  facet_grid(cols = vars(Method))+    # Set legend title
  xlab("Signal Strength")+ 
  ylab("FDR")+
  ylim(0,1)+
  theme_bw()+
  geom_hline(yintercept=0.1, linetype="dashed", 
            color = "black", size=0.5)+
  labs(colour = "Sample Size")+
  theme(legend.text = element_text(size=5))
ggsave("Fig5d.png", units="in", width=13, height=2, dpi=300)
```

# Association Analysis

```{r}
# Figure S7a
ds_mirk = read.csv('../table/twosample/strongsig-mirk.csv')[-10,-1]
ds_perm = read.csv('../table/twosample/strongsig-perm.csv')[-10,-1]

res1 = c()
res2 = c()
for(k in 1:ncol(ds_perm)){
  res1 = c(res1,ds_perm[,k])
  res2 = c(res2,ds_mirk[,k])
}

res1 = data.frame('Power'=res1)
res2 = data.frame('Power'=res2)

res1$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))
res2$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))

k = 9
res1$m = c(rep(100,k),rep(300,k),rep(500,k))
res2$m = c(rep(100,k),rep(300,k),rep(500,k))
res1$Test = rep('PERMANOVA',3*k)
res2$Test = rep('MiRKAT',3*k)
res = rbind(res1,res2)
res$Method = factor(res$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'))


ggplot(data=res, aes(x=as.factor(m), y=Power, fill=Method))+
geom_bar(stat="identity",
         position=position_dodge(),
         size=.3,
        ) +                        # Thinner lines
scale_fill_brewer(palette = "Set3")+
facet_grid(cols = vars(Test))+    # Set legend title
xlab("Sample size") + 
ylab("Power")+
coord_flip()+
theme_bw()+
theme(legend.text = element_text(size=10))

```

```{r}
# Figure 4b
ds_mirk = read.csv('../table/twosample/weaksig-mirk.csv')[-10,-1]
ds_perm = read.csv('../table/twosample/weaksig-perm.csv')[-10,-1]

res1 = c()
res2 = c()
for(k in 1:ncol(ds_perm)){
  res1 = c(res1,ds_perm[,k])
  res2 = c(res2,ds_mirk[,k])
}

res1 = data.frame('Power'=res1)
res2 = data.frame('Power'=res2)

res1$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))
res2$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))


k = 9
res1$m = c(rep(100,k),rep(300,k),rep(500,k))
res2$m = c(rep(100,k),rep(300,k),rep(500,k))
res1$Test = rep('PERMANOVA',3*k)
res2$Test = rep('MiRKAT',3*k)
res = rbind(res1,res2)
res$Method = factor(res$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'))


ggplot(data=res, aes(x=as.factor(m), y=Power, fill=Method))+
geom_bar(stat="identity",
         position=position_dodge(),
         size=.3,
        ) +                        # Thinner lines
scale_fill_brewer(palette = "Set3")+
facet_grid(cols = vars(Test))+    # Set legend title
xlab("Sample size") + 
ylab("Power")+
coord_flip()+
theme_bw()+
theme(legend.text = element_text(size=10))
ggsave("Fig4b.png", units="in", width=7, height=4, dpi=300)
```

```{r}
# Figure S7b
ds_mirk = read.csv('../table/twosample/contsig-mirk.csv')[-10,-1]
ds_perm = read.csv('../table/twosample/contsig-perm.csv')[-10,-1]

res1 = c()
res2 = c()
for(k in 1:ncol(ds_perm)){
  res1 = c(res1,ds_perm[,k])
  res2 = c(res2,ds_mirk[,k])
}

res1 = data.frame('Power'=res1)
res2 = data.frame('Power'=res2)

res1$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))
res2$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))

k = 9
res1$m = c(rep(100,k),rep(300,k),rep(500,k))
res2$m = c(rep(100,k),rep(300,k),rep(500,k))
res1$Test = rep('PERMANOVA',3*k)
res2$Test = rep('MiRKAT',3*k)
res = rbind(res1,res2)
res$Method = factor(res$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'))


ggplot(data=res, aes(x=as.factor(m), y=Power, fill=Method))+
geom_bar(stat="identity",
         position=position_dodge(),
         size=.3,
        ) +                        # Thinner lines
scale_fill_brewer(palette = "Set3")+
facet_grid(cols = vars(Test))+    # Set legend title
xlab("Sample size") + 
ylab("Power")+
coord_flip()+
theme_bw()+
theme(legend.text = element_text(size=10))

```

```{r}
# Figure 4a
ds_mirk = read.csv('../table/twosample/sc-mirk.csv')[,-1]
ds_perm = read.csv('../table/twosample/sc-perm.csv')[,-1]

ds_mirk = ds_mirk[-10,]
ds_perm = ds_perm[-10,]
res1 = c()
res2 = c()
for(k in 1:ncol(ds_perm)){
  res1 = c(res1,ds_perm[,k])
  res2 = c(res2,ds_mirk[,k])
}
res1 = data.frame('Power'=res1)
res2 = data.frame('Power'=res2)
res1$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))
res2$Method =  rep(c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'),ncol(ds_perm))
k = 9
res1$c = c(rep(1,k),rep(2,k),rep(3,k))
res2$c = c(rep(1,k),rep(2,k),rep(3,k))
res1$Test = rep('PERMANOVA',3*k)
res2$Test = rep('MiRKAT',3*k)
res = rbind(res1,res2)
res$Method = factor(res$Method,level = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction'))

## plot

ggplot(data=res, aes(x=as.factor(c), y=Power, fill=Method))+
geom_bar(stat="identity",
         position=position_dodge(),
         size=.3) +                        # Thinner lines
scale_fill_brewer(palette = "Set3")+ 
facet_grid(cols = vars(Test))+    # Set legend title
xlab("Sampling Fraction Difference") + 
ylab("Type I Error")+
coord_flip()+
theme_bw()+
theme(legend.text = element_text(size=10))+
geom_hline(yintercept=0.05, linetype="dashed", 
            color = "red", size=1)
ggsave("Fig4a.png", units="in", width=7, height=4, dpi=300)
```

