---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(biomformat)
library(stringr)
library(ape)
library(phyloseq)
library(MicrobiomeStat)
library(ggVennDiagram)
library(edgeR)
library(dada2)
library(microbiome)
library(viridis)
library(RDB)
library(ggplot2)
library(patchwork)
```

```{r}
source("../Algorithm.R")
```

```{r}
##data preprocessing

filepath <- "../../data/Vangay/"
folders<-list.files(path = filepath)

filep<-paste(filepath,"/","reference-hit.biom", sep = "")
x = read_biom(filep)


treep<-paste(filepath,"/","insertion_tree.relabelled.tre", sep = "")
treefile = readChar(treep,file.info(treep)$size)
str_count(treefile, pattern = '; ')
treefile2 = gsub('; ','|',treefile)
tree = read.tree(text=treefile2)
nalength=is.na(tree$edge.length)
nonzerolength=tree$edge.length!=0
tree$edge.length[nalength]=sample(tree$edge.length[(!nalength)&nonzerolength], sum(nalength))

sum(tree$edge.length==0 & tree$edge[,2]<=length(tree$tip.label))
meta = read.delim(paste(filepath,"/","12080_20210508-071948.txt", sep = ""))
samplenames <- sapply(x$columns, function(y){y$id})
meta <- meta[meta$sample_name %in% samplenames,]
meta$bmi_class[meta$bmi_class=='Obese'] = 'Overweight'

otu <- sapply(x$rows, function(y){y$id})
drop_tips <- tree$tip.label[!(tree$tip.label %in% otu)]
tree <- ape::drop.tip(tree,drop_tips) %>% ape::as.phylo()
P <- sapply(x$data, function(y,subsamplenames){y[subsamplenames]}, subsamplenames = meta$sample_name)
colnames(P) <- otu
P = t(P)


P = P[rowSums(P)>0,]
rownames(meta) = meta$sample_name

#taxonomy = assignTaxonomy(rownames(P), "../data/silva_nr99_v138.1_train_set.fa.gz", multithread=TRUE)
taxonomy = read.csv(paste(filepath,"/","taxonomy.csv", sep = ""),row.names=1)
```

```{r}
OTU = otu_table(P,taxa_are_rows=T) # matrix
META = sample_data(meta) # data frame
PHYLO = phy_tree(tree) # tree (list)
TAXA = tax_table(as.matrix(taxonomy))
physeq = phyloseq(OTU,TAXA,META, PHYLO) 
```


# Normalization

```{r}
P.list = Normalized(P,eta=0.01)
```

```{r}
P1 = P.list[[2]] # data normalized by rsim
rownames(P1) = rownames(P)
colnames(P1) = colnames(P)
OTU = otu_table(P1,taxa_are_rows=T) # matrix
physeq1 = phyloseq(OTU,TAXA, META, PHYLO) 
```

# PCoA-Figure 3c

```{r}
mds.plot = function(A,gl,main,pvalue){
  dist_matrix = dist(t(A))
  mds.stuff = cmdscale(dist_matrix, eig=T, x.ret=T)
  mds.var.per = round(mds.stuff$eig/sum(mds.stuff$eig)*100,1)
  mds.values = mds.stuff$points
  mds.data = data.frame(Sample=rownames(mds.values),
                         X=mds.values[,1],
                         Y=mds.values[,2],
                        Group = gl)


  ggplot(data=mds.data, aes(x=X, y=Y,col=Group))+
    geom_point(size=0.5)+
    xlab(paste("PCoA1 -", mds.var.per[1], '%', sep=""))+
    ylab(paste("PCoA2 -", mds.var.per[2], '%', sep=""))+
    ggtitle(label = main, subtitle = paste("p-value: ",pvalue))+
    theme_bw()
}
```


```{r}
set.seed(100)
P.kt = P[,which(meta$sample_group=='KarenThai')]
sequence_depth = as.data.frame(colSums(P.kt))
ind1 = which(sequence_depth<5000)
ind2 = which(sequence_depth>10000)
P_sub = P[,c(ind1,ind2)]
meta_sub = meta[c(ind1,ind2),]
Y = as.factor(c(rep(1,length(ind1)),rep(2,length(ind2))))
pvalue = c()
for(i in 1:length(P.list)){
  P2 = P.list[[i]]
  P2 = P2[,which(meta$sample_group=='KarenThai')]
  P_sub = P2[,c(ind1,ind2)]
  Y1 = Y[!is.na(colSums(P_sub))]
  P_sub1 = P_sub[,!is.na(colSums(P_sub))]
  dist_matrix = dist(t(P_sub1))
  df.Y = as.data.frame(Y1)
  Re = adonis2(dist_matrix~Y1, data = df.Y,permutations = 9999)
  pvalue = c(pvalue,Re$`Pr(>F)`[1])
  print(Re$`Pr(>F)`[1])
}
```

```{r}
save(P.list,file = "3cData.RData")
```


```{r}
method.list = c('RSim','Unnormalized','CSS','MED','TMM','TSS','UQ','GMPR','Rarefaction')
p = NULL
Y = as.factor(c(rep("<5000",length(ind1)),rep(">10000",length(ind2))))
for(i in 1:length(P.list)){
  P2 = P.list[[i]]
  P2 = P2[,which(meta$sample_group=='KarenThai')]
  P_sub = P2[,c(ind1,ind2)]
  Y1 = Y[!is.na(colSums(P_sub))]
  P_sub1 = P_sub[,!is.na(colSums(P_sub))]
  if(is.null(p)){
    p = mds.plot(log(P_sub1+1),Y1,method.list[i],pvalue[i])
  }else{
    p = p + mds.plot(log(P_sub1+1),Y1,method.list[i],pvalue[i])
  }
}

p+ plot_layout(ncol = 9,guides = "collect")& theme(legend.position = "bottom") 
ggsave("../figure/Fig3c.png", units="in", width=15, height=2.7, dpi=300)
```

# Association Test-Table 1

```{r}
set.seed(100)
meta_sub = meta[meta$sample_group == 'KarenThai',]
Y = meta_sub$bmi
pvalue = c()
for(i in 1:length(P.list)){
  P2 = P.list[[i]]
  P2 = P2[,which(meta$sample_group == 'KarenThai')]
  Y1 = Y[!is.na(colSums(P2))]
  P2.1 = P2[,!is.na(colSums(P2))]
  dist_matrix = dist(t(P2.1))
  df.Y = as.data.frame(Y1)
  Re = adonis2(dist_matrix~Y1, data = df.Y, permutations = 9999)
  pvalue = c(pvalue,Re$`Pr(>F)`[1])
  print(Re$`Pr(>F)`[1])
}
```

```{r}
set.seed(100)
meta_sub = meta[meta$sample_group == 'KarenThai',]
Y = meta_sub$bmi
pvalue1 = c()
for(i in 1:length(P.list)){
  P2 = P.list[[i]]
  P2 = P2[,which(meta$sample_group == 'KarenThai')]
  Y1 = Y[!is.na(colSums(P2))]
  P2.1 = P2[,!is.na(colSums(P2))]
  dist_matrix = dist(t(P2.1))
  kerlP <- D2K(as.matrix(dist_matrix))
  Re = MiRKAT(y = Y1, Ks = kerlP)
  pvalue1 = c(pvalue1,Re$p_values)
  print(Re$p_values)
}
```

```{r}
res = data.frame("PERMANOVA" = pvalue, "MiRKAT" = pvalue1)

#write.csv(res,"KarenThai_bmi.csv")
```

# Differential Abundant Test-Table S1

```{r}
physeq.g = aggregate_taxa(physeq,"Phylum")
physeq.g1 = aggregate_taxa(physeq1,"Phylum")
```

```{r}
## Karen and Karen1st
pseq = subset_samples(physeq.g,(ethnicity == "Karen"))
pseq1 = subset_samples(physeq.g1,(ethnicity == "Karen"))
X = as.matrix(otu_table(pseq)@.Data)
X.rsim = as.matrix(otu_table(pseq1)@.Data)
X = X[rowSums(X)>0,]
X.rsim = X.rsim[rowSums(X.rsim)>0,]
Y = sample_data(pseq)$sample_group
data = as.data.frame(cbind(t(X),Y))
data1 = as.data.frame(cbind(t(X.rsim),Y))

rdb.res = rdb(t(X),as.numeric(as.factor(Y))-1,alpha = 0.1,fdr=T)

t_p <- sapply(1:(ncol(data)-1), function(i)t.test(as.numeric(data[, i]) ~ Y, data = data)$p.value)
p1.1 <- p.adjust(t_p, method='BH')
t_res = which(p1.1<0.1)

t_p <- sapply(1:(ncol(data1)-1), function(i)t.test(as.numeric(data1[, i]) ~ Y, data = data1)$p.value)
p1.1 <- p.adjust(t_p, method='BH')
t_res.rsim = which(p1.1<0.1)

DA.res = data.frame("Phylum" = unique(c(rownames(X.rsim)[t_res.rsim], rownames(X)[rdb.res],rownames(X)[t_res])))
DA.res$rsim = DA.res$Phylum%in%rownames(X.rsim)[t_res.rsim]
DA.res$rdb = DA.res$Phylum%in%rownames(X)[rdb.res]
DA.res$t = DA.res$Phylum%in%rownames(X)[t_res]
```


